version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot_gym
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:13
    container_name: postgres_db_gym
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  postgres_data:
